name: unittest-with-hana

on: push
jobs:
  test:

    runs-on: self-hosted
    timeout-minutes: 15
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-test-local-hana-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: npm install
      run: npm ci

    - name: npm install driver
      run: |
        npm install -D @sap/hana-client
        npm install -D hdb-pool
      
    - name: npm build
      run: npm run build

    - name: npm test
      run: npm run coverage
      env:
        CI: true
        HANA_USER: ODATASERVER
        HANA_PASSWORD: ${{ secrets.LOCAL_HANA_PWD }}
        HANA_HOST: hxehost
        HANA_PORT: 39015
        DEBUG: "@sap*"
