name: unittest-with-hana

on: push
jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm ci

    - name: npm install driver
      run: npm install -S hdb-pool @sap/hana-client
      
    - name: npm build
      run: npm run build

    - name: npm test
      run: npm run coverage
      env:
        CI: true
        HANA_USER: ${{ secrets.CLOUD_HANA_USER }}
        HANA_PASSWORD: ${{ secrets.CLOUD_HANA_PWD }}
        HANA_HOST: ${{ secrets.CLOUD_HANA_HOST }}
        HANA_PORT: ${{ secrets.CLOUD_HANA_PORT }}
        HANA_CLOUD_VERIFY: true
        DEBUG: '@odata/server*'
