name: unittest-with-mysql

on: push
jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_DATABASE: odata_test
          MYSQL_USER: odata_test
          MYSQL_PASSWORD: odata_test
          MYSQL_ROOT_PASSWORD: odata_test_root_password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=30s --health-timeout=5s --health-retries=10

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-test-mysql-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: npm install
      run: npm ci

    - name: npm install driver
      run: |
        npm install -D mysql@2.18.1

    - name: npm build
      run: npm run build

    - name: npm test
      run: npm run coverage
      env:
        CI: true
        MYSQL_USER: odata_test
        MYSQL_PASSWORD: odata_test
        MYSQL_DATABASE: odata_test
        MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        TEST_DB_LOG: true

